<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\Ktp $model
 */

$this->title = 'Surat Pengantar e-KTP ' . $model->nik_nama;
$this->params['breadcrumbs'][] = ['label' => 'Surat Pengantar e-KTP', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->nik_nama, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud ktp-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'Daftar Ktp', ['index'], ['class' => 'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="box box-info">
        <div class="box-body">
            <?php $this->beginBlock('app\models\Ktp'); ?>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'nik',
                    'nik_nama',
                    'nik_tempat_lahir',
                    'nik_tanggal_lahir',
                    'nik_jenis_kelamin',
                    'nik_pekerjaan',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'agama',
                        'value' => ($model->getNikAgama()->one()->nama_agama),
                    ],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'status_perkawinan',
                        'value' => ($model->getNikStatusPerkawinan()->one()->status_perkawinan),
                    ],
                    'nik_kewarganegaraan',
                    'nik_alamat:ntext',
                    'rt',
                    'rw',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat

                ],
            ]); ?>

            <hr/>

            <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id],
                [
                    'class' => 'btn btn-danger',
                    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
                    'data-method' => 'post',
                ]); ?>
            <?php $this->endBlock(); ?>



            <?= Tabs::widget(
                [
                    'id' => 'relation-tabs',
                    'encodeLabels' => false,
                    'items' => [[
                        'label' => '<b class=""># ' . $model->nik_nama . '</b>',
                        'content' => $this->blocks['app\models\Ktp'],
                        'active' => true,
                    ],]
                ]
            );
            ?>
        </div>
    </div>
</div>
