<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\web\View;
use \dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\Ktp $model
 * @var yii\widgets\ActiveForm $form
 */

?>

    <div class="box box-info">
        <div class="box-body">
            <?php $form = ActiveForm::begin([
                    'id' => 'Ktp',
                    'layout' => 'horizontal',
                    'enableClientValidation' => true,
                    'errorSummaryCssClass' => 'error-summary alert alert-error'
                ]
            );
            ?>

            <?= $form->field($model, 'nik')->widget(\app\components\NikFinderWidgetV2::className(), [
                "pilihan" => [
                    'nama',
                    'jenis_kelamin',
                    'gol_darah',
                    'tempat_lahir',
                    'tanggal_lahir',
                    'alamat',
                    'rt',
                    'rw',
                    'kel_desa',
                    'kecamatan',
                    'agama',
                    'status_perkawinan',
                    'pekerjaan',
                    'kewarganegaraan',
                ]
            ]); ?>
            <?= $form->field($model, 'nik_nama')->textInput(['maxlength' => true, 'readOnly' => true]) ?>
            <?= $form->field($model, 'nik_tempat_lahir')->textInput(['maxlength' => true, 'readOnly' => true]) ?>
            <?= $form->field($model, 'nik_tanggal_lahir')->textInput(['readOnly' => true]) ?>
            <?= $form->field($model, 'nik_jenis_kelamin')->textInput(['maxlength' => true, 'readOnly' => true]) ?>
            <?= $form->field($model, 'nik_pekerjaan')->textInput(['readOnly' => true]) ?>
            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
            $form->field($model, 'nik_agama')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\Agama::find()->all(), 'id', 'nama_agama'),
                ['prompt' => 'Select'
                    , 'readOnly' => true]
            ); ?>
            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
            $form->field($model, 'nik_status_perkawinan')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\StatusPerkawinan::find()->all(), 'id', 'status_perkawinan'),
                ['prompt' => 'Select'
                    , 'readOnly' => true]
            ); ?>
            <?= $form->field($model, 'nik_kewarganegaraan')->textInput(['maxlength' => true, 'readOnly' => true]) ?>
            <?= $form->field($model, 'nik_alamat')->textarea(['rows' => 6, 'readOnly' => true]) ?>
            <hr/>
            <?php echo $form->errorSummary($model); ?>
            <div class="row">
                <div class="col-md-offset-3 col-md-10">
                    <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                    <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
                </div>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
<?php


?>