<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use app\components\Angka;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\IuranSearch $searchModel
 */
$this->title = 'Iuran';
$this->params['breadcrumbs'][] = $this->title;
?>

<p>
</p>
<?php
$jumIuran = 0;
foreach (\app\models\Iuran::find()->all() as $jm1) {
    $jumIuran += $jm1->nominal;
}
?>

<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
<p class='pull-left'>
    <?= Html::a('<i class="fa fa-plus"></i> Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?></p>
<p class="pull-right">
    <?php echo "Total Iuran : Rp " . Angka::toReadableAngka($jumIuran, false) ?>
</p>

<div class="clearfix"></div>
<div class="box box-info">
    <div class="box-body">
        <div class="table-responsive">
            <?=
            GridView::widget([
                'layout' => '{summary}{pager}{items}{pager}',
                'dataProvider' => $dataProvider,
                'pager' => [
                    'class' => yii\widgets\LinkPager::className(),
                    'firstPageLabel' => 'First',
                    'lastPageLabel' => 'Last'],
                'filterModel' => $searchModel,
                'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                'headerRowOptions' => ['class' => 'x'],
                'columns' => [

                    \app\components\ActionButton::getButtons(),
                    // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'contentOptions' => ['nowrap' => 'nowrap', 'style' => 'text-align:center'],
                        'attribute' => 'Tanggal',
                        'value' => function ($model) {
                            return \app\components\Tanggal::indonesian_date(new \DateTime($model->tanggal));
                        },
                        'format' => 'raw',
                    ],
                    'nik',
                    'nama',
                    'nominal',
                    'keterangan:ntext',
                    // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
                ],
            ]);
            ?>
        </div>
    </div>
</div>

<?php \yii\widgets\Pjax::end() ?>

