<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\Penduduk $model
 */
$this->title = 'Penduduk ' . $model->nama;
$this->params['breadcrumbs'][] = ['label' => 'Penduduk', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->nama, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud penduduk-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'Daftar Penduduk', ['index'], ['class' => 'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="box box-info">
        <div class="box-body">
            <?php $this->beginBlock('app\models\Penduduk'); ?>

            <?=
            DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'nik',
                    'nama',
                    'jenis_kelamin',
                    'gol_darah',
                    'tempat_lahir',
                    'tanggal_lahir',
                    'alamat:ntext',
                    'rt',
                    'rw',
                    'kel_desa',
                    'kecamatan',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'agama',
                        'value' => ($model->getAgama0()->one()->nama_agama),
                    ],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'status_perkawinan',
                        'value' => ($model->getStatusPerkawinan()->one()->status_perkawinan),
                    ],
                    'pekerjaan',
                    'kewarganegaraan',
                ],
            ]);
            ?>

            <hr/>

            <?=
            Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data-confirm' => '' . 'Are you sure to delete this item?' . '',
                'data-method' => 'post',
            ]);
            ?>
            <?php $this->endBlock(); ?>



            <?php $this->beginBlock('Iurans'); ?>
            <div style='position: relative'><div style='position:absolute; right: 0px; top:0px;'>
                    <?=
                    Html::a(
                            '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Iuran', ['iuran/index'], ['class' => 'btn text-muted btn-xs']
                    )
                    ?>
                    <?=
                    Html::a(
                            '<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru' . ' Iuran', ['iuran/create', 'Iuran' => ['nik' => $model->nik]], ['class' => 'btn btn-success btn-xs']
                    );
                    ?>
                </div></div><?php Pjax::begin(['id' => 'pjax-Iurans', 'enableReplaceState' => false, 'linkSelector' => '#pjax-Iurans ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
            <?=
            '<div class="table-responsive">' . \yii\grid\GridView::widget([
                'layout' => '{summary}{pager}<br/>{items}{pager}',
                'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getIurans(), 'pagination' => ['pageSize' => 20, 'pageParam' => 'page-iurans']]),
                'pager' => [
                    'class' => yii\widgets\LinkPager::className(),
                    'firstPageLabel' => 'First',
                    'lastPageLabel' => 'Last'
                ],
                'columns' => [[
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update}',
                'contentOptions' => ['nowrap' => 'nowrap'],
                'urlCreator' => function ($action, $model, $key, $index) {
            // using the column name as key, not mapping to 'id' like the standard generator
            $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
            $params[0] = 'iuran' . '/' . $action;
            return $params;
        },
                'buttons' => [
                ],
                'controller' => 'iuran'
                    ],
                    'nama',
                    'nominal',
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'contentOptions' => ['nowrap' => 'nowrap', 'style' => 'text-align:center'],
                        'attribute' => 'Tanggal',
                        'value' => function ($model) {
                            return \app\components\Tanggal::indonesian_date(new \DateTime($model->tanggal));
                        },
                        'format' => 'raw',
                    ],
                    'keterangan:ntext',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
                ],
            ]) . '</div>'
            ?>
            <?php Pjax::end() ?>
            <?php $this->endBlock() ?>


            <?php $this->beginBlock('Tamuses'); ?>
            <div style='position: relative'><div style='position:absolute; right: 0px; top:0px;'>
                    <?=
                    Html::a(
                            '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Tamu', ['tamu/index'], ['class' => 'btn text-muted btn-xs']
                    )
                    ?>
                    <?=
                    Html::a(
                            '<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru' . ' Tamu', ['tamu/create', 'Tamus' => ['dituju' => $model->id]], ['class' => 'btn btn-success btn-xs']
                    );
                    ?>
                </div></div><?php Pjax::begin(['id' => 'pjax-Tamuses', 'enableReplaceState' => false, 'linkSelector' => '#pjax-Tamuses ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
            <?=
            '<div class="table-responsive">' . \yii\grid\GridView::widget([
                'layout' => '{summary}{pager}<br/>{items}{pager}',
                'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getTamus(), 'pagination' => ['pageSize' => 20, 'pageParam' => 'page-tamuses']]),
                'pager' => [
                    'class' => yii\widgets\LinkPager::className(),
                    'firstPageLabel' => 'First',
                    'lastPageLabel' => 'Last'
                ],
                'columns' => [[
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update}',
                'contentOptions' => ['nowrap' => 'nowrap'],
                'urlCreator' => function ($action, $model, $key, $index) {
            // using the column name as key, not mapping to 'id' like the standard generator
            $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
            $params[0] = 'tamu' . '/' . $action;
            return $params;
        },
                'buttons' => [
                ],
                'controller' => 'tamu'
                    ],
                    'nik_tamu',
                    'nama_tamu',
                    'keperluan:ntext',
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'contentOptions' => ['nowrap' => 'nowrap', 'style' => 'text-align:center'],
                        'attribute' => 'Tanggal',
                        'value' => function ($model) {
                            return \app\components\Tanggal::indonesian_date(new \DateTime($model->tanggal));
                        },
                        'format' => 'raw',
                    ],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
                    
                        ]
                    ]) . '</div>'
                    ?>
                    <?php Pjax::end() ?>
                    <?php $this->endBlock() ?>


                    <?=
                    Tabs::widget(
                            [
                                'id' => 'relation-tabs',
                                'encodeLabels' => false,
                                'items' => [ [
                                        'label' => '<b class=""># ' . $model->nama . '</b>',
                                        'content' => $this->blocks['app\models\Penduduk'],
                                        'active' => true,
                                    ], [
                                        'content' => $this->blocks['Iurans'],
                                        'label' => '<small>Iuran <span class="badge badge-default">' . count($model->getIurans()->asArray()->all()) . '</span></small>',
                                        'active' => false,
                                    ], [
                                        'content' => $this->blocks['Tamuses'],
                                        'label' => '<small>Tamu <span class="badge badge-default">' . count($model->getTamus()->asArray()->all()) . '</span></small>',
                                        'active' => false,
                                    ],]
                            ]
                    );
                    ?>
        </div>
    </div>
</div>
