<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use kartik\select2\Select2;

/**
 * @var yii\web\View $this
 * @var app\models\Tamu $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="box box-info">
    <div class="box-body">
        <?php
        $form = ActiveForm::begin([
                    'id' => 'Tamu',
                    'layout' => 'horizontal',
                    'enableClientValidation' => true,
                    'errorSummaryCssClass' => 'error-summary alert alert-error'
                        ]
        );
        ?>
        <?= $form->field($model, 'nik_tamu')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'nama_tamu')->textInput(['maxlength' => true]) ?>
        <?=
        // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
        $form->field($model, 'dituju')->widget(Select2::className(), [
            'data' => \yii\helpers\ArrayHelper::map(app\models\Penduduk::find()->all(), 'id', 'nama'),
            'language' => 'de',
            'options' => ['placeholder' => 'Pilih Penduduk ...'],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]);
        ?>
        <?= $form->field($model, 'keperluan')->textarea(['rows' => 6]) ?>
        <hr/>
      
        <div class="row">
            <div class="col-md-offset-3 col-md-10">
                <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>